name: Publish to NPM

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm i -ff

      - run: npm publish --access public

        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
